### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by bhalazs** [thiagopbueno/tf-mpc#9]
Hey, I wanted to check the documentation at https://tfmpc.readthedocs.io/, but it is not there anymore. Any chance you could provide it somehow? Would love to try out your repo for my research :)

**Comment by thiagopbueno** [comment]
Hi @bhalazs ,

Thanks for your interest in my repo.

I will eventually update the overall documentation after some refactoring... But as I'm completely engulfed with my thesis' writing right now, I'm afraid I will only have the bandwidth to do that in a month or so...

Cheers!

**Comment by bhalazs** [comment]
Thank you, looking forward to it, and good luck with your thesis!
